%% 
%% 
%% 
%% plot2.m
% Reads f.bin generated by main2 and plots it as a 2D surface.

filename = 'f.bin';
if ~isfile(filename)
    error('File %s not found. Please run main2 first.', filename);
end

fid = fopen(filename, 'rb');

% Read dimensions (main2.cpp writes 3 ints, even for 2D data)
dims = fread(fid, 3, 'int32');

% Create the grid coordinates
nx = dims(1);
ny = dims(2);
nz = dims(3);
x = linspace(0, 1, nx);
y = linspace(0, 1, ny);
z = linspace(0, 1, nz);
[X, Y, Z] = meshgrid(x, y, z);

% Read the float data
data = fread(fid, inf, 'single');
fclose(fid);
F = permute(reshape(data, nx, ny, nz), [ 3 2 1 ]);

fid = fopen('P.bin', 'rb');
fread(fid, 3, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
P = permute(reshape(data, nx, ny, nz), [ 3 2 1 ]);

fid = fopen('w.bin', 'rb');
fread(fid, 3, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
W = permute(reshape(data, nx, ny, nz), [ 3 2 1 ]);

fid = fopen('M.bin', 'rb');
num_M = fread(fid, 1, 'uint64');
data = fread(fid, 3 * num_M, 'single');
fclose(fid);
M = reshape(data, 3, num_M);


% Force displayed volume to be unit cube
ax = gca;
ax.XLim = [0 1];
ax.YLim = [0 1];
ax.ZLim = [0 1];
t = ax.CameraTarget;           % camera target
v = ax.CameraPosition - t;     % view vector from target to camera
%ax.CameraPosition = t + 2*v;   % move camera twice as far from target

% Make data units equal in all directions and prevent autoscaling on rotate
daspect([1 1 1])      % equal data-unit aspect ratio
axis vis3d           % freeze aspect ratio and limits during rotation
xlabel('x'); ylabel('y'); zlabel('z');

figure;
plot3(M(1, :), M(2, :), M(3, :), 'r.', 'MarkerSize', 10);
%Create the isosurface at 0.5
p = isosurface(X, Y, Z, P, 0.1);
patch(p, 'FaceColor', 'blue', 'EdgeColor', 'none', 'FaceAlpha', 0.2);
p = isosurface(X, Y, Z, P, 0.3);
patch(p, 'FaceColor', 'blue', 'EdgeColor', 'none', 'FaceAlpha', 0.2);
p = isosurface(X, Y, Z, P, 0.5);
patch(p, 'FaceColor', 'blue', 'EdgeColor', 'none', 'FaceAlpha', 0.2);
p = isosurface(X, Y, Z, P, 0.7);
patch(p, 'FaceColor', 'blue', 'EdgeColor', 'none', 'FaceAlpha', 0.2);
p = isosurface(X, Y, Z, P, 0.9);
patch(p, 'FaceColor', 'blue', 'EdgeColor', 'none', 'FaceAlpha', 0.2);

% axis tight;
daspect([1 1 1]);
view(3);
drawnow;
