%% 
%% 
%% 
%% plot2.m
% Reads f.bin generated by main2 and plots it as a 2D surface.

filename = 'f.bin';
if ~isfile(filename)
    error('File %s not found. Please run main2 first.', filename);
end

fid = fopen(filename, 'rb');

% Read dimensions (main2.cpp writes 3 ints, even for 2D data)
dims = fread(fid, 2, 'int32');
nx = dims(1);
ny = dims(2);

% Read the float data
data = fread(fid, inf, 'single');
fclose(fid);
F = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('P.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
P = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('w.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
W = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('f1.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
f1 = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('f2.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
f2 = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('S1.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
S1 = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('S2.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
S2 = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('T1.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
T1 = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('T2.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
T2 = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('R.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
R = permute(reshape(data, nx, ny), [2 1]);

fid = fopen('M.bin', 'rb');
num_M = fread(fid, 1, 'uint64');
data = fread(fid, 2 * num_M, 'single');
fclose(fid);
M = reshape(data, 2, num_M);

% fid = fopen('L.bin', 'rb');
% fread(fid, 2, 'int32'); % Skip dimensions header
% data = fread(fid, inf, 'single');
% fclose(fid);
% L = permute(reshape(data, nx, ny), [2 1]);

% Create grid coordinates
x = linspace(0, 1, nx);
y = linspace(0, 1, ny);
[X, Y] = meshgrid(x, y);

% Plot
figure;
surf(X, Y, W);
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('Weights w(x, y)');

figure;
surf(X, Y, F); % Transpose F to match meshgrid (X varies across columns)
shading interp;
view(2); % Top-down view
colorbar;
axis([0 1 0 1]);
axis square;
xlabel('x');
ylabel('y');
title('Function f(x, y)');

figure;
surf(X, Y, f1);
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('f1(x, y)');

figure;
surf(X, Y, f2);
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('f2(x, y)');

figure;
surf(X, Y, S1);
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('S1(x, y)');

figure;
surf(X, Y, S2);
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('S2(x, y)');

figure;
surf(X, Y, T1);
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('T1(x, y)');

figure;
surf(X, Y, T2);
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('T2(x, y)');

figure;
surf(X, Y, R);
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('R(x, y)');

% figure;
% surf(X, Y, L);
% shading interp;
% view(2);
% colorbar;
% axis([0 1 0 1]);
% axis square;
% title('Laplacian(x, y)');

figure;
hold on;

contour(X, Y, P, 0.1:0.1:0.9, 'k');
contour(X, Y, P, [0.001 0.001], 'b');
% contour(X, Y, S1', [0 0], 'b', 'LineWidth', 2);
% contour(X, Y, S2', [0 0], 'g', 'LineWidth', 2);
% contour(X, Y, L', [0 0], 'g', 'LineWidth', 2);
plot(M(1, :), M(2, :), 'r.', 'MarkerSize', 10);

axis([0 1 0 1]);
axis square;
title('P(x, y) with modal boundaries');
hold off
% figure;
% surf(X, Y, S1');
% shading interp;
% view(2);
% hold on;
% contour(X, Y, P', 0.1:0.1:0.9, 'k');
% hold off;
% colorbar;
% axis([0 1 0 1]);
% axis square;
% title('S1(x, y) surface with P contours');
