%% 
%% 
%% 
%% plot2.m
% Reads f.bin generated by main2 and plots it as a 2D surface.

filename = 'f.bin';
if ~isfile(filename)
    error('File %s not found. Please run main2 first.', filename);
end

fid = fopen(filename, 'rb');

% Read dimensions (main2.cpp writes 3 ints, even for 2D data)
dims = fread(fid, 2, 'int32');
nx = dims(1);
ny = dims(2);

% Read the float data
data = fread(fid, inf, 'single');
fclose(fid);
F = reshape(data, nx, ny);

fid = fopen('P.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
P = reshape(data, nx, ny);

fid = fopen('w.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
W = reshape(data, nx, ny);

fid = fopen('f1.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
f1 = reshape(data, nx, ny);

fid = fopen('f2.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
f2 = reshape(data, nx, ny)

fid = fopen('S1.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
S1 = reshape(data, nx, ny);

fid = fopen('S2.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
S2 = reshape(data, nx, ny);

fid = fopen('T1.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
T1 = reshape(data, nx, ny);

fid = fopen('T2.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
T2 = reshape(data, nx, ny);

fid = fopen('M.bin', 'rb');
fread(fid, 2, 'int32'); % Skip dimensions header
data = fread(fid, inf, 'single');
fclose(fid);
M = reshape(data, nx, ny);

% Create grid coordinates
x = linspace(0, 1, nx);
y = linspace(0, 1, ny);
[X, Y] = meshgrid(x, y);

% Plot
figure;
surf(X, Y, W');
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('Weights w(x, y)');

figure;
surf(X, Y, F'); % Transpose F to match meshgrid (X varies across columns)
shading interp;
view(2); % Top-down view
colorbar;
axis([0 1 0 1]);
axis square;
xlabel('x');
ylabel('y');
title('Function f(x, y)');

figure;
surf(X, Y, f1');
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('f1(x, y)');

figure;
surf(X, Y, f2');
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('f2(x, y)');

figure;
surf(X, Y, S1');
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('S1(x, y)');

figure;
surf(X, Y, S2');
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('S2(x, y)');

figure;
surf(X, Y, T1');
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('T1(x, y)');

figure;
surf(X, Y, T2');
shading interp;
view(2);
colorbar;
axis([0 1 0 1]);
axis square;
title('T2(x, y)');

figure;
contour(X, Y, P', 0.1:0.1:0.9, 'k');
hold on;
% contour(X, Y, S1', [0 0], 'b', 'LineWidth', 2);
% contour(X, Y, S2', [0 0], 'g', 'LineWidth', 2);
contour(X, Y, M', [0 0], 'r', 'LineWidth', 2);
hold off;
axis([0 1 0 1]);
axis square;
title('P(x, y) with modal boundaries');

% figure;
% surf(X, Y, S1');
% shading interp;
% view(2);
% hold on;
% contour(X, Y, P', 0.1:0.1:0.9, 'k');
% hold off;
% colorbar;
% axis([0 1 0 1]);
% axis square;
% title('S1(x, y) surface with P contours');
